--- #YAML:1.0
name:               Text-YAWikiFormater
version:            0.50
abstract:           The great new Text::YAWikiFormater!
author:
    - Marco Neves <perl-cpan@fwd.avidmind.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTML::Entities:  0
    JSON:            0
    Test::More:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
